[project]
name = "agentic-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "arize-phoenix>=13.0.3",
    "asyncpg>=0.31.0",
    "beautifulsoup4>=4.14.3",
    "chromadb>=1.5.0",
    "deepeval>=3.8.4",
    "docling>=2.74.0",
    "faiss-cpu>=1.13.2",
    "fastapi>=0.129.0",
    "flashrank>=0.2.10",
    "gradio>=6.6.0",
    "gunicorn>=25.1.0",
    "httpx>=0.28.1",
    "ipykernel>=7.2.0",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.13",
    "langchain-docling>=2.0.0",
    "langchain-google-genai>=4.2.0",
    "langchain-huggingface>=1.2.0",
    "langchain-openai>=1.1.10",
    "langchain-pinecone>=0.2.13",
    "langchain-text-splitters>=1.1.0",
    "langgraph>=1.0.8",
    "langsmith>=0.7.4",
    "loguru>=0.7.3",
    "mcp>=1.26.0",
    "mypy>=1.19.1",
    "pandas>=2.3.3",
    "passlib[bcrypt]>=1.7.4",
    "pinecone>=7.3.0",
    "prometheus-client>=0.24.1",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.0",
    "pymupdf>=1.27.1",
    "pypdf>=6.7.1",
    "pytest>=9.0.2",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.1",
    "python-jose[cryptography]>=3.5.0",
    "python-json-logger>=4.0.0",
    "pyyaml>=6.0.3",
    "ragas>=0.4.3",
    "rank-bm25>=0.2.2",
    "redis>=7.2.0",
    "ruff>=0.15.1",
    "sentence-transformers>=5.2.3",
    "sqlalchemy>=2.0.46",
    "streamlit>=1.54.0",
    "tenacity>=9.1.4",
    "uvicorn>=0.41.0",
]
